version: '3.7'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5440:5440
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/dumps:/dumps

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.django_app
    restart: always
    volumes:
    - ./backend:/app
    command: bash -c ". /venv/bin/activate && python /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
    - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react_server
    restart: always
    volumes:
    - ./frontend:/app
    command: bash -c "cd /app && npm start"
    depends_on:
      - db
      - backend
    ports:
    - 3000:3000

  redis:
    image: redis:5.0.7
    restart: always
    depends_on:
      - db
    ports:
      - 6379:6379