# Generated by Django 2.2.4 on 2019-10-15 13:05

import apps.films.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poster_file', models.ImageField(upload_to=apps.films.utils.get_film_poster_address)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('average_rate', models.IntegerField(default=0)),
                ('age_rate', models.IntegerField()),
                ('film_file', models.FileField(upload_to=apps.films.utils.get_film_address)),
                ('film_company', models.CharField(max_length=50)),
                ('producing_country', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('premiere', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
                ('visits_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trailer_file', models.FileField(upload_to=apps.films.utils.get_film_trailer_address)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('film', models.ManyToManyField(related_name='languages', to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('film', models.ManyToManyField(related_name='genres', to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=apps.films.utils.get_film_image_address)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='films.Film')),
            ],
        ),
    ]
