# Generated by Django 2.2.4 on 2019-10-21 11:03

import apps.films.validators
import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20191021_1103'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.RemoveField(
            model_name='language',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='actors.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='films.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='languages',
            field=models.ManyToManyField(related_name='films', to='films.Language'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_file',
            field=models.FileField(null=True, upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field, validators=[apps.films.validators.validate_film_file_type]),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_file',
            field=models.ImageField(null=True, upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field),
        ),
        migrations.AlterField(
            model_name='filmimage',
            name='image_file',
            field=models.ImageField(null=True, upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_file',
            field=models.FileField(null=True, upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field),
        ),
    ]
