# Generated by Django 2.2.4 on 2019-10-18 13:00

import apps.films.utils
import apps.films.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_file',
            field=models.FileField(upload_to=apps.films.utils.get_film_address, validators=[apps.films.validators.validate_film_file_type]),
        ),
    ]
