# Generated by Django 2.2.4 on 2019-10-15 13:05

import apps.film_reviews.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mark', models.IntegerField(validators=[apps.film_reviews.validators.validate_mark])),
                ('context', models.TextField(max_length=1000)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.Film')),
            ],
        ),
    ]
