# Generated by Django 2.2.4 on 2019-10-21 09:55

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field)),
                ('descripption', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ActorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.utils.SetAddressFunctionsClass.set_address_for_file_field)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='actors.Actor')),
            ],
        ),
    ]
