# Generated by Django 2.2.3 on 2019-08-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='poster',
            new_name='poster_file',
        ),
        migrations.RenameField(
            model_name='filmimage',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='filmimage',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='trailer',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trailer',
            old_name='film',
            new_name='trailer_file',
        ),
    ]
