# Generated by Django 2.2.3 on 2019-08-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_auto_20190801_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
