# Generated by Django 2.2.3 on 2019-08-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190801_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='photo',
        ),
    ]
