# Generated by Django 2.2.3 on 2019-08-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190805_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='avatar',
        ),
    ]
